export const savedAddresses = [
  {
    id: "home",
    type: "Home",
    firstName: "Alex",
    lastName: "Smith",
    line1: "123 Tech Avenue, Suite 400",
    city: "San Francisco",
    state: "CA",
    postalCode: "94105",
    country: "United States",
    phone: "+1 (415) 555-0182",
    isDefault: true,
  },
  {
    id: "work",
    type: "Work",
    firstName: "Alex",
    lastName: "Smith",
    line1: "500 Market Street, Floor 12",
    city: "San Francisco",
    state: "CA",
    postalCode: "94105",
    country: "United States",
    phone: "+1 (415) 555-0294",
    isDefault: false,
  },
  {
    id: "other",
    type: "Other",
    firstName: "Alex",
    lastName: "Smith",
    line1: "88 Pine Street, Apt 3B",
    city: "New York",
    state: "NY",
    postalCode: "10005",
    country: "United States",
    phone: "+1 (212) 555-0371",
    isDefault: false,
  },
];
