import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { StarRating } from "./star-rating";
import type { Review } from "./types";

type ReviewFormValues = { rating: number; title: string; body: string; pros: string; cons: string };
export function ReviewDialog({ product, review, onClose }: { product: string; review: Review | null; onClose: () => void }) { const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<ReviewFormValues>({ defaultValues: { rating: review?.rating ?? 0, title: review?.title ?? "", body: review?.body ?? "", pros: "", cons: "" } }); const rating = watch("rating"); const onSubmit = (values: ReviewFormValues) => { void values; /* Connect to the review create/update API. */ onClose(); }; return <div className="fixed inset-0 z-50 grid place-items-center p-4"><Button type="button" variant="ghost" className="absolute inset-0 size-auto rounded-none bg-black/50 backdrop-blur-sm hover:bg-black/50" onClick={onClose} aria-label="Close review dialog" /><form onSubmit={handleSubmit(onSubmit)} className="relative w-full max-w-lg rounded-2xl bg-card shadow-2xl"><header className="border-b border-border p-6"><h2 className="text-lg font-bold uppercase">{review ? "Edit Review" : "Write a Review"}</h2><p className="text-sm text-muted-foreground">{product}</p></header><div className="space-y-5 p-6"><div><Label className="mb-2">Overall rating</Label><StarRating rating={rating} interactive onChange={(value) => setValue("rating", value, { shouldValidate: true })} />{rating === 0 && <p className="mt-1 text-xs text-destructive">Choose a rating</p>}</div><div><Label htmlFor="review-title" className="mb-2">Review title</Label><Input id="review-title" {...register("title", { required: "A review title is required" })} />{errors.title && <p className="mt-1 text-xs text-destructive">{errors.title.message}</p>}</div><div><Label htmlFor="review-body" className="mb-2">Your review</Label><Textarea id="review-body" rows={5} {...register("body", { required: "Tell us about your experience", minLength: { value: 20, message: "Use at least 20 characters" } })} />{errors.body && <p className="mt-1 text-xs text-destructive">{errors.body.message}</p>}</div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="pros" className="mb-2">Pros</Label><Input id="pros" placeholder="Fast, great build quality" {...register("pros")} /></div><div><Label htmlFor="cons" className="mb-2">Cons</Label><Input id="cons" placeholder="Runs hot, expensive" {...register("cons")} /></div></div></div><footer className="flex gap-3 p-6 pt-0"><Button type="button" variant="outline" className="flex-1" onClick={onClose}>Cancel</Button><Button type="submit" className="flex-1" disabled={!rating}>{review ? "Save changes" : "Submit review"}</Button></footer></form></div>; }
